name: Update Archive Index

on:
  push:
    paths:
      - 'daily/*.html'    # Only run when daily HTML files change

permissions:
  contents: write

jobs:
  update-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Find latest HTML file
      id: findfile
      run: |
        latest_file=$(ls -t daily/*.html | head -n 1)
        echo "latest_file=$latest_file" >> $GITHUB_ENV
        echo "Latest file: $latest_file"

    - name: Update archive.html
      run: |
        # Find newest file by filename (YYYY-MM-DD.html), not mod time
        latest_file=$(ls daily/*.html | sort -r | head -n 1)
        file_name=$(basename "$latest_file")
        file_date="${file_name%.html}"
        pretty_date=$(date -d "$file_date" +"%B %d, %Y")

        echo "Latest file by filename: $file_name"

        # TEMP: Always insert for testing (remove this if you want duplicate check back)
        sed -i "0,/<ul[^>]*>/s//<ul>\n  <li><a href=\"daily\/$file_name\">$pretty_date<\/a><\/li>/" archive.html
        
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add archive.html
        git diff --quiet && echo "No changes to commit." || git commit -m "Add $file_name to archive"
        git push
